services:
  - type: web
    name: product-attribution-backend
    env: python
    repo: https://github.com/thebiggestcookie/product-attribution-matching
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    plan: free
    region: oregon

  - type: web
    name: product-attribution-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 16.15.0
    plan: free

version: "1"
